version: "3.8"

services:
  estimate_postgres:
    container_name: estimate_postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=estimate
    ports:
      - "5433:5432"
    volumes:
      - estimate_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak_postgres_1:
    container_name: keycloak_postgres_1
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak_1
    ports:
      - "5432:5432"
    volumes:
      - keycloak_postgres_data_1:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak_1:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_1
    environment:
      - KC_DATABASE=postgres
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres_1:5432/keycloak_1
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8484:8080"
    depends_on:
      - keycloak_postgres_1
    volumes:
      - keycloak_data_1:/opt/keycloak/data_1
      - ./keycloak_export_1:/opt/keycloak_export_1
    command: start-dev
    restart: unless-stopped

  estimate-app:
    image: payk96/estimate:0.0.1
    build:
      context: .
    container_name: estimate-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://estimate_postgres:5432/estimate
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_APPLICATION_NAME=estimate
      - KEYCLOAK_URL=http://keycloak_1:8080/auth
      - KEYCLOAK_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0M+auAxobI46uLcDRAmFksSMBs5DyAuvuILuQk/SLkL0SALBGtaJG97/EBcwHFtavglXa/oCNxP44F8x1GbRC11QLvH+CxDG0GD+hHFKbTmrhKwc9IkLksgoG4cHmwrJHvefqbvcy0wS6g3sFK2Jl7Tr5fo5H26ZnJzA/Pl4Gi8zv7rscwX5XjGaT1Uzg2+2+Ls0eSHaNV+5GQNaIwpy+yGcEketEFSWeVwLLw9relZghNp/4Ck4Hf+CbsDNHgWBKT+voAvJb6DfUIM7KDf1AGkkTs9szKXapTvYUy6Td2qAqCX/WztDR+IgH7/o4Dryr9YZLWPPXX9xH5pf+V7j1QIDAQAB
      - CLIENT_ID=estimate-app
      - GRANT_TYPE=password
      - RESOURCE_URL=http://keycloak_1:8080/realms/estimate/protocol/openid-connect/token
    depends_on:
      - estimate_postgres
      - keycloak_1
    restart: unless-stopped


volumes:
  keycloak_data_1:
  keycloak_postgres_data_1:
  estimate_postgres_data:

