version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: "estimate_postgres"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=estimate_db
    restart: always
volumes:
  db_data: