apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimate-app
  namespace: estimate360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estimate-app
  template:
    metadata:
      labels:
        app: estimate-app
    spec:
      containers:
        - name: estimate-app
          image: payk96/estimate:0.0.8
          ports:
            - containerPort: 8081
          env:
            - name: KEYCLOAK_PUBLIC_KEY
              value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmHC1Lwvz9nJKCwFSmBWWAxFhAfqnScchSStAqv3fMSgsWrsmje9IBWyj7XVL+7YwQwmUEXJPnAxlIY/CT5J7bAYc5c00ptm5+2Q/yHYdWAHFqBPZ47t0IylEGpWCr6YrgiDa4HXCMTAK7tO1YkzgfLHY+Stb0kBfyiJMV0k12UHF8afvjleOBBdGHZXF35kv4X42FE38fkdg1b0b5iFDDRLLNIUmgy4ApTSt8Rec81KwjDBAGqh4Y6F4geVpBOg57unCCbz4IkcH6KGeFIDsoKSzAxaPdqnO8dLGsN6HEGDhkht92SyHrDSbAiqgcREa0EbATmi3uATyEiCNsvJJwwIDAQAB
            - name: CLIENT_ID
              value: estimate-app
            - name: KEYCLOAK_TOKEN_URL
              value: https://estimate360.stk8s.66bit.ru/auth/realms/estimate/protocol/openid-connect/token
            - name: SPRING_DATASOURCE_ESTIMATE_URL
              value: jdbc:postgresql://estimate-postgres-service:5432/estimate
            - name: SPRING_DATASOURCE_KEYCLOAK_URL
              value: jdbc:postgresql://keycloak-postgres-service:5432/keycloak_1
            - name: KEYCLOAK_REDIRECT_URI
              value: https://estimate360.stk8s.66bit.ru/quiz

---
apiVersion: v1
kind: Service
metadata:
  name: estimate-app-service
  namespace: estimate360
spec:
  selector:
    app: estimate-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
