apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimate-app
  namespace: estimate360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estimate-app
  template:
    metadata:
      labels:
        app: estimate-app
    spec:
      containers:
        - name: estimate-app
          image: payk96/estimate:0.0.5
          ports:
            - containerPort: 8081
          env:
            - name: KEYCLOAK_PUBLIC_KEY
              value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlM4AAguoiOaY9QDZFcvTFRN8F7KxaIjGXKlxcgUxNpY3Smx2kuC+Wbp6aqDk/5OrXwLgm7o6Jqy6aYelc7IP4dbCD0642D5wycO456/afrgxnZQ+HOsaQ+d900oSIFaCu41qZ23ncqgvZ4yn325CE/JyQENFcw0RRk9PllmN1cxWMAStSotkn3P2lpizC+8W47Y4Oj57yRhGDTmWzsPtwdvVKjvqSzeApFNuHQsumectbmqEHHGHzA+CXAEjTJRPy+/0oixRpOMQco9Mb0YPzx9XQuV0BgHXLSDvn71btdzBX1zfkvMjNpN9OIFrgy68FIl7gKFAEHYeT+aNvUM8tQIDAQAB
            - name: CLIENT_ID
              value: estimate-app
            - name: KEYCLOAK_TOKEN_URL
              value: http://keycloak-1:8080/realms/estimate/protocol/openid-connect/token
            - name: SPRING_DATASOURCE_ESTIMATE_URL
              value: jdbc:postgresql://estimate-postgres:5432/estimate
            - name: SPRING_DATASOURCE_KEYCLOAK_URL
              value: jdbc:postgresql://keycloak-postgres-1:5432/keycloak_1
---
apiVersion: v1
kind: Service
metadata:
  name: estimate-app-service
  namespace: estimate360
spec:
  selector:
    app: estimate-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
